services:
  - type: web
    name: whats-my-stdby
    env: node
    plan: free
    buildCommand: npm install && npx playwright install chromium --with-deps && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
